org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC

# Найстрокйи проекта
java_version=25
project_group=com.zfettostudios.zfuctone
project_name=zFuctone
project_version=0.1-SHAPSHOT
project_authors=zFetto Studios
project_website=https://zfettostudios.com/project/zfuctone
project_description=A powerful core for easily creating your own extensions
project_path_libraries=com.zfettostudios.zfuctone.library

# Модули
module_core=core
module_bootstrap=bootstrap
module_java=java
module_minecraft_bukkit=minecraft-bukkit

# Paper
# https://papermc.io/downloads/paper
# https://artifactory.papermc.io/ui/native/universe/io/papermc/paper/paper-api/
paper_version=26.3.build.37-alpha

# Velocity
# https://papermc.io/downloads/velocity
# https://artifactory.papermc.io/ui/native/universe/com/velocitypowered/velocity-api/
velocity_version=4.2.1-SNAPSHOT

# PaperWeight
# https://plugins.gradle.org/m2/io/papermc/paperweight/paperweight-userdev/
paperweight_userdev=2.0.0-beta.23

# Jackson
# https://github.com/FasterXML
# https://repo.maven.apache.org/maven2/tools/jackson/core/jackson-core/
jackson_version=3.2.2

# Jackson Annotations
# https://github.com/FasterXML
# https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/
jackson_annotations_version=2.22

# SnakeYaml Engine
# https://repo.maven.apache.org/maven2/org/snakeyaml/snakeyaml-engine/
snakeyaml_version=3.1.1

# Lombok
# https://projectlombok.org/
# https://repo.maven.apache.org/maven2/org/projectlombok/lombok/
lombok_version=1.18.48

# Kyori Adventure
# https://repo.maven.apache.org/maven2/net/kyori/adventure-api/
adventure_version=5.2.0

# Kyori Ansi
# https://repo.maven.apache.org/maven2/net/kyori/ansi/
ansi_version=1.1.1

# ObjectWeb Asm
# https://repo.maven.apache.org/maven2/org/ow2/asm/asm
asm_version=9.10.1

# ByteBuddy
# https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/
bytebuddy_version=1.18.14

# Lucko Jar Relocator
# https://repo.maven.apache.org/maven2/me/lucko/jar-relocator/
lucko_jar_relocator_version=1.7

# zJAnots
# https://github.com/zFettoStudios/zJAnots
zjanots_version=0.1.1

# zJTime
# https://github.com/zFettoStudios/zJTime
zjtime_version=0.1.2

# Gradle Shadow
# https://plugins.gradle.org/m2/com/gradleup/shadow/com.gradleup.shadow.gradle.plugin/
gradle_shadow_version=9.6.1

# Gradle Toolchains
# https://plugins.gradle.org/m2/org/gradle/toolchains/foojay-resolver-convention/org.gradle.toolchains.foojay-resolver-convention.gradle.plugin/
gradle_toolchains_version=1.0.0

# BuildConfig
# https://plugins.gradle.org/m2/com/github/gmazzo/buildconfig/com.github.gmazzo.buildconfig.gradle.plugin/
buildconfig_version=6.1.1

# Репозитории
maven_repository=https://repo.maven.apache.org/maven2/
maven_2_repository=https://repo1.maven.org/maven2/
sonatype_repository=https://oss.sonatype.org/content/groups/public/
papermc_repository=https://repo.papermc.io/repository/maven-public/
spigotmc_repository=https://hub.spigotmc.org/nexus/content/repositories/snapshots/
jitpack_repository=https://jitpack.io/